-include $(BUILD_ROOT)/Svc/ImgComp/inc.mk

EXTRA_INC_DIRS_SvcImgComptestut_DARWIN := $(EXTRA_INC_DIRS_SvcImgComptestut_DARWIN) $(EXTRA_INC_DIRS_DARWIN) $(EXTRA_INC_DIRS)
EXTRA_LIBS_SvcImgComptestut_DARWIN := $(EXTRA_LIBS_SvcImgComptestut_DARWIN) $(EXTRA_LIBS_DARWIN) $(EXTRA_LIBS)

EXTRA_INC_DIRS_SvcImgComptestut_SDFLIGHT := $(EXTRA_INC_DIRS_SvcImgComptestut_SDFLIGHT) $(EXTRA_INC_DIRS_SDFLIGHT) $(EXTRA_INC_DIRS)
EXTRA_LIBS_SvcImgComptestut_SDFLIGHT := $(EXTRA_LIBS_SvcImgComptestut_SDFLIGHT) $(EXTRA_LIBS_SDFLIGHT) $(EXTRA_LIBS)

EXTRA_INC_DIRS_SvcImgComptestut_LINUX := $(EXTRA_INC_DIRS_SvcImgComptestut_LINUX) $(EXTRA_INC_DIRS_LINUX) $(EXTRA_INC_DIRS)
EXTRA_LIBS_SvcImgComptestut_LINUX := $(EXTRA_LIBS_SvcImgComptestut_LINUX) $(EXTRA_LIBS_LINUX) $(EXTRA_LIBS)

EXTRA_INC_DIRS_DARWIN=
EXTRA_LIBS_DARWIN=
EXTRA_INC_DIRS_SDFLIGHT=
EXTRA_LIBS_SDFLIGHT=
EXTRA_INC_DIRS_LINUX=
EXTRA_LIBS_LINUX=
EXTRA_INC_DIRS=
EXTRA_LIBS=
