HEXAGON_DSP_TYPE := ADSP
HEXAGON_V_ARCH := v55

HEXAGON_ARCH_LINK_FLAGS := -march=hexagon -mcpu=hexagon$(HEXAGON_V_ARCH)

HEXAGON_ARCH_CPU_FLAGS := -m$(HEXAGON_V_ARCH) -G0 -DDSP_TYPE_$(HEXAGON_DSP_TYPE)

HEXAGON_ARCH_LIB_DIR := $(HEXAGON_TOOLS_ROOT)/target/hexagon/lib/$(HEXAGON_V_ARCH)/G0/pic
#$(HEXAGON_TOOLS_ROOT)/target/hexagon/lib/v5/G0/pic

HEXAGON_ARCH_INCLUDES := -I $(HEXAGON_SDK_ROOT)/libs/common/qurt/ADSP$(HEXAGON_V_ARCH)MP/include #\
