-include $(BUILD_ROOT)/ROS/fprime_ws/src/SIMREF/mod.mk

EXTRA_INC_DIRS_SIMREFRotorSDrv_DARWIN := $(EXTRA_INC_DIRS_SIMREFRotorSDrv_DARWIN) $(EXTRA_INC_DIRS_DARWIN) $(EXTRA_INC_DIRS)
EXTRA_LIBS_SIMREFRotorSDrv_DARWIN := $(EXTRA_LIBS_SIMREFRotorSDrv_DARWIN) $(EXTRA_LIBS_DARWIN) $(EXTRA_LIBS)

EXTRA_INC_DIRS_DARWIN=
EXTRA_LIBS_DARWIN=
EXTRA_INC_DIRS=
EXTRA_LIBS=
