#include "AEEStdDef.idl"

interface hexref
{
  long init();
  long run();
  long fini();

  typedef sequence<octet, 1024> dataBuffer;

  long rpc_relay_port_allocate(in long size);
  //long rpc_relay_port_deallocate(); //TODO(mereweth) - do this on close?
  long rpc_relay_port_read(rout long port, rout dataBuffer buff, rout long bytes);

  long rpc_relay_buff_allocate(in long size);
  //long rpc_relay_buff_deallocate(); //TODO(mereweth) - do this on close?
  long rpc_relay_buff_read(rout long port, rout dataBuffer buff, rout long bytes);
  
  long rpc_relay_write(in long port, in dataBuffer buff);
};

