/*
 * SerialTextConverterImplCfg.hpp
 *
 *  Created on: Jan 11, 2018
 *      Author: mereweth
 */

#ifndef SERIALTEXTCONVERTER_SERIALTEXTCONVERTERIMPLCFG_HPP_
#define SERIALTEXTCONVERTER_SERIALTEXTCONVERTERIMPLCFG_HPP_

enum {
    STC_READ_BUFF_SIZE = 40,
};

#endif /* SERIALTEXTCONVERTER_SERIALTEXTCONVERTERIMPLCFG_HPP_ */
