EXTRA_INC_DIRS_LINUX = $(TURBOJPEG_INCLUDE)
EXTRA_INC_DIRS_DARWIN = $(TURBOJPEG_INCLUDE)

EXTRA_LIBS_SDFLIGHT = $(HEXAGON_ARM_SYSROOT)/usr/lib/libturbojpeg.a

EXTRA_LIBS_LINUX = $(TURBOJPEG_LIB)
EXTRA_LIBS_DARWIN = $(TURBOJPEG_LIB)
